### PR TITLE
ask function will behave like listen if text is empty

### PR DESCRIPTION
**Pull request by Eikosa**

### CODE REVIEW

**Comment by usernein** [comment]
Hmm why would someone use ask() with empty text and why the check should be made on pyromod and not on the bot code?

**Comment by Eikosa** [comment]
> Hmm why would someone use ask() with empty text and why the check should be made on pyromod and not on the bot code?

I thought it would be nice if we don't write anything inside the function, like the input() function in python itself, that it just takes input

**Comment by Eikosa** [comment]
Also, maybe if something like this is added, the listen function may not be needed

**Comment by usernein** [comment]
> > Hmm why would someone use ask() with empty text and why the check should be made on pyromod and not on the bot code?
> 
> I thought it would be nice if we don't write anything inside the function, like the input() function in python itself, that it just takes input

That makes sense

**Comment by usernein** [comment]
Thanks for your contribution! It's going to be added in pyromod v3 release (coming soon)

**Pull request merged**
